links:
- confidence: 0.9
  direction: negative
  peer: CVX
  relation: integrated_with
  source: CRV
- confidence: 0.95
  direction: negative
  peer: AAVE
  relation: entity_exposure
  source: CRV
- confidence: 0.4
  direction: negative
  peer: SNX
  relation: integrated_with
  source: CRV
- confidence: 0.95
  direction: negative
  peer: SOL
  relation: entity_exposure
  source: FTT
- confidence: 0.97
  direction: negative
  peer: SRM
  relation: entity_exposure
  source: FTT
- confidence: 0.6
  direction: negative
  peer: BNB
  relation: competitor
  source: FTT
- confidence: 0.9
  direction: negative
  peer: CRV
  relation: entity_exposure
  source: AAVE
- confidence: 0.7
  direction: negative
  peer: UNI
  relation: competitor
  source: CRV
- confidence: 0.8
  direction: negative
  peer: SUSHI
  relation: competitor
  source: UNI
- confidence: 0.8
  direction: negative
  peer: UNI
  relation: competitor
  source: SUSHI
- confidence: 0.6
  direction: negative
  peer: BAL
  relation: competitor
  source: UNI
- confidence: 0.6
  direction: negative
  peer: BAL
  relation: competitor
  source: CRV
- confidence: 0.8
  direction: negative
  peer: COMP
  relation: competitor
  source: AAVE
- confidence: 0.8
  direction: negative
  peer: AAVE
  relation: competitor
  source: COMP
- confidence: 0.6
  direction: negative
  peer: MKR
  relation: competitor
  source: AAVE
- confidence: 0.8
  direction: negative
  peer: LINK
  relation: shares_oracle
  source: AAVE
- confidence: 0.8
  direction: negative
  peer: LINK
  relation: shares_oracle
  source: COMP
- confidence: 0.6
  direction: negative
  peer: LINK
  relation: shares_oracle
  source: CRV
- confidence: 0.7
  direction: negative
  peer: LINK
  relation: shares_oracle
  source: SNX
- confidence: 0.5
  direction: negative
  peer: COMP
  relation: same_ecosystem
  source: AAVE
- confidence: 0.5
  direction: negative
  peer: SNX
  relation: same_ecosystem
  source: SUSHI
- confidence: 0.99
  direction: negative
  peer: LUNA
  relation: collateral_of
  source: UST
- confidence: 0.9
  direction: negative
  peer: ANC
  relation: same_ecosystem
  source: UST
- confidence: 0.85
  direction: negative
  peer: MIR
  relation: same_ecosystem
  source: UST
- confidence: 0.6
  direction: negative
  peer: AVAX
  relation: entity_exposure
  source: UST
- confidence: 0.55
  direction: negative
  peer: CRV
  relation: integrated_with
  source: UST
- confidence: 0.9
  direction: negative
  peer: MKR
  relation: entity_exposure
  source: USDC
- confidence: 0.8
  direction: negative
  peer: CRV
  relation: integrated_with
  source: USDC
- confidence: 0.7
  direction: negative
  peer: COMP
  relation: collateral_of
  source: USDC
- confidence: 0.7
  direction: negative
  peer: AAVE
  relation: collateral_of
  source: USDC
- confidence: 0.5
  direction: negative
  peer: SNX
  relation: integrated_with
  source: USDC
