"""initial tables

Revision ID: 687629483785
Revises: 
Create Date: 2026-03-16 01:34:16.549966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687629483785'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('bar_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bars'))
    )
    op.create_index('ix_bars_symbol', 'bars', ['symbol'], unique=False)
    op.create_index('ix_bars_timestamp_symbol', 'bars', ['timestamp', 'symbol'], unique=False)
    op.create_table('geopolitical_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('goldstein_scale', sa.Float(), nullable=True),
    sa.Column('num_mentions', sa.Integer(), nullable=False),
    sa.Column('num_sources', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geopolitical_events'))
    )
    op.create_index('ix_geopolitical_events_country_code', 'geopolitical_events', ['country_code'], unique=False)
    op.create_index('ix_geopolitical_events_event_date', 'geopolitical_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_geopolitical_events_event_id'), 'geopolitical_events', ['event_id'], unique=True)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_articles'))
    )
    op.create_index(op.f('ix_news_articles_article_id'), 'news_articles', ['article_id'], unique=True)
    op.create_index('ix_news_articles_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('ix_news_articles_symbol', 'news_articles', ['symbol'], unique=False)
    op.create_table('signal_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=False),
    sa.Column('macd_histogram', sa.Float(), nullable=False),
    sa.Column('macd_line', sa.Float(), nullable=False),
    sa.Column('macd_signal', sa.Float(), nullable=False),
    sa.Column('bb_position', sa.Float(), nullable=False),
    sa.Column('bb_upper', sa.Float(), nullable=False),
    sa.Column('bb_lower', sa.Float(), nullable=False),
    sa.Column('atr', sa.Float(), nullable=False),
    sa.Column('momentum_5', sa.Float(), nullable=False),
    sa.Column('vol_regime', sa.String(length=8), nullable=False),
    sa.Column('vol_regime_confidence', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('combined_alpha', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_snapshots'))
    )
    op.create_index('ix_signal_snapshots_symbol', 'signal_snapshots', ['symbol'], unique=False)
    op.create_index('ix_signal_snapshots_timestamp_symbol', 'signal_snapshots', ['timestamp', 'symbol'], unique=False)
    op.create_table('ticks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticks'))
    )
    op.create_index('ix_ticks_symbol', 'ticks', ['symbol'], unique=False)
    op.create_index('ix_ticks_timestamp_symbol', 'ticks', ['timestamp', 'symbol'], unique=False)
    op.create_table('trade_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('pnl_usd', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('slippage_usd', sa.Float(), nullable=False),
    sa.Column('fees_usd', sa.Float(), nullable=False),
    sa.Column('rsi_at_entry', sa.Float(), nullable=False),
    sa.Column('macd_at_entry', sa.Float(), nullable=False),
    sa.Column('sentiment_at_entry', sa.Float(), nullable=False),
    sa.Column('social_velocity_at_entry', sa.Float(), nullable=False),
    sa.Column('gdelt_intensity_at_entry', sa.Float(), nullable=False),
    sa.Column('vol_regime_at_entry', sa.String(length=8), nullable=False),
    sa.Column('combined_alpha_at_entry', sa.Float(), nullable=False),
    sa.Column('params_version', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('exit_reason', sa.String(length=32), nullable=False),
    sa.Column('failure_mode', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_records'))
    )
    op.create_index('ix_trade_records_entry_time', 'trade_records', ['entry_time'], unique=False)
    op.create_index('ix_trade_records_exit_time', 'trade_records', ['exit_time'], unique=False)
    op.create_index('ix_trade_records_symbol', 'trade_records', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_records_trade_id'), 'trade_records', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_records_trade_id'), table_name='trade_records')
    op.drop_index('ix_trade_records_symbol', table_name='trade_records')
    op.drop_index('ix_trade_records_exit_time', table_name='trade_records')
    op.drop_index('ix_trade_records_entry_time', table_name='trade_records')
    op.drop_table('trade_records')
    op.drop_index('ix_ticks_timestamp_symbol', table_name='ticks')
    op.drop_index('ix_ticks_symbol', table_name='ticks')
    op.drop_table('ticks')
    op.drop_index('ix_signal_snapshots_timestamp_symbol', table_name='signal_snapshots')
    op.drop_index('ix_signal_snapshots_symbol', table_name='signal_snapshots')
    op.drop_table('signal_snapshots')
    op.drop_index('ix_news_articles_symbol', table_name='news_articles')
    op.drop_index('ix_news_articles_published_at', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_article_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_geopolitical_events_event_id'), table_name='geopolitical_events')
    op.drop_index('ix_geopolitical_events_event_date', table_name='geopolitical_events')
    op.drop_index('ix_geopolitical_events_country_code', table_name='geopolitical_events')
    op.drop_table('geopolitical_events')
    op.drop_index('ix_bars_timestamp_symbol', table_name='bars')
    op.drop_index('ix_bars_symbol', table_name='bars')
    op.drop_table('bars')
    # ### end Alembic commands ###
