#!/usr/bin/env python3
"""Script to review and approve/reject pending trade proposals.

This is the human-in-the-loop approval interface. Pending proposals
generated by the strategy engine are listed here for manual review
before execution.

Usage::

    python scripts/approve_proposals.py
    # Or:
    qts approve
"""

from __future__ import annotations

import sys

if __name__ == "__main__":
    from qts.cli.main import main

    sys.exit(main(["approve"] + sys.argv[1:]))  # type: ignore[call-arg]
